// Narration.
//
// Notes on the timeline are the script; this turns them into speech and puts
// that speech on an audio track at the frame each note is pinned to.
//
// The speech itself is generated by Kokoro in the main process (see
// electron/ipc/voice.ts) — locally, with no account and no upload, which
// matters because narration is usually written against something unreleased.
//
// Everything here is honest about not being available: with no desktop bridge,
// or with the model not yet downloaded, these report what is missing and what
// to do about it rather than returning silence that looks like success.

import type { CommentModel } from "./comments";
import { narratableComments } from "./comments";
import { type AssetModel, assetFromRecording } from "./media";

export interface VoiceStatus {
	installed: boolean;
	installing: boolean;
	progress: number | null;
	modelId: string;
	cacheDir: string;
	bytes: number;
	error?: string;
}

/** The default voice. Kokoro's warmest English one, and its own default. */
export const DEFAULT_VOICE = "af_heart";

function voiceBridge() {
	return typeof window === "undefined" ? undefined : window.electronAPI;
}

export function voiceSupported(): boolean {
	return typeof voiceBridge()?.speak === "function";
}

const UNAVAILABLE =
	"Speech needs Rendr's desktop app — the model runs in the main process, which a browser tab has no access to.";

export async function getVoiceStatus(): Promise<VoiceStatus> {
	const bridge = voiceBridge();
	if (!bridge?.voiceStatus) {
		return {
			installed: false,
			installing: false,
			progress: null,
			modelId: "",
			cacheDir: "",
			bytes: 0,
			error: UNAVAILABLE,
		};
	}
	return bridge.voiceStatus() as Promise<VoiceStatus>;
}

/**
 * One-click setup: downloads the model if this machine has never had it.
 *
 * Safe to call when it is already installed — it loads from the cache and
 * returns, so "set up voices" is one button whatever state the machine is in.
 */
export async function installVoice(
	onProgress?: (ratio: number) => void,
): Promise<{ ok: boolean; error?: string }> {
	const bridge = voiceBridge();
	if (!bridge?.installVoice) return { ok: false, error: UNAVAILABLE };

	const stop = onProgress ? bridge.onVoiceProgress?.(onProgress) : undefined;
	try {
		const result = await bridge.installVoice();
		if (result?.error) return { ok: false, error: result.error };
		return { ok: Boolean(result?.installed) };
	} catch (error) {
		return { ok: false, error: error instanceof Error ? error.message : String(error) };
	} finally {
		stop?.();
	}
}

/** Speaks one line and returns it as a library asset, ready to place. */
export async function speakToAsset(
	text: string,
	options: { voice?: string; speed?: number; name?: string } = {},
): Promise<{ asset: AssetModel; seconds: number; voiceId: string }> {
	const bridge = voiceBridge();
	if (!bridge?.speak) throw new Error(UNAVAILABLE);

	const line = await bridge.speak(text, {
		voice: options.voice ?? DEFAULT_VOICE,
		speed: options.speed ?? 1,
	});

	// base64 → bytes → Blob. The main process sends base64 because IPC carries
	// structured data, not streams, and a line of speech is a few hundred KB.
	const binary = atob(line.wavBase64);
	const bytes = new Uint8Array(binary.length);
	for (let index = 0; index < binary.length; index++) bytes[index] = binary.charCodeAt(index);
	const blob = new Blob([bytes], { type: "audio/wav" });

	const asset = assetFromRecording(
		blob,
		options.name ?? shortName(text),
		line.seconds,
		0,
		0,
		false,
		true,
	);
	// It came from a model, not from a capture — the library shouldn't offer it
	// cursor telemetry or treat it as a take.
	return {
		asset: { ...asset, type: "audio", fromRecording: false },
		seconds: line.seconds,
		voiceId: line.voiceId,
	};
}

/** A short label from the line itself, so the library is readable. */
function shortName(text: string): string {
	const trimmed = text.trim().replace(/\s+/g, " ");
	return trimmed.length <= 42 ? trimmed : `${trimmed.slice(0, 40)}…`;
}

export interface NarrationPlanEntry {
	comment: CommentModel;
	/** Frame the line starts at — the note's own frame. */
	startFrame: number;
	/** Skipped, and why. */
	skipped?: string;
}

/**
 * What narrating the timeline would do, without doing it.
 *
 * Notes already voiced from the same text are skipped: re-speaking them would
 * burn a minute of CPU to produce the identical file, and would replace a take
 * the user may have already positioned by hand.
 */
export function planNarration(
	comments: readonly CommentModel[],
	options: { regenerate?: boolean } = {},
): NarrationPlanEntry[] {
	return narratableComments(comments).map((comment) => {
		const alreadyCurrent =
			comment.voice !== undefined && comment.voice.fromText === comment.text;
		return {
			comment,
			startFrame: comment.frame,
			...(alreadyCurrent && !options.regenerate
				? { skipped: "already voiced from this text" }
				: {}),
		};
	});
}

/**
 * How long a line will run, near enough to lay out a timeline before speaking.
 *
 * Kokoro's pace is close to natural English at speed 1. This is only used to
 * warn about lines that will overrun the gap to the next note — the real
 * duration replaces it as soon as the audio exists.
 */
export function estimateSeconds(text: string, speed = 1): number {
	const words = text.trim().split(/\s+/).filter(Boolean).length;
	if (words === 0) return 0;
	// ~165 wpm, plus a beat of lead-in and tail.
	return (words / 165) * 60 * (1 / Math.max(0.5, speed)) + 0.35;
}

/**
 * Notes whose speech would run into the next note.
 *
 * Reported rather than fixed: shortening the line is a writing decision and
 * moving the note is an editing one, and guessing which the user wanted is how
 * narration ends up out of step with the picture.
 */
export function overrunWarnings(
	comments: readonly CommentModel[],
	fps: number,
	speed = 1,
	/**
	 * Real durations by comment id, once the lines have actually been spoken.
	 *
	 * The estimate is only for laying out a timeline *before* generating. Once
	 * the audio exists its true length is known, and reporting the guess instead
	 * overstates the problem — on the first real run this claimed a 1.44 s
	 * overrun where the truth was 0.4 s, which is the kind of number that gets
	 * a warning ignored.
	 */
	measured?: ReadonlyMap<string, number>,
): Array<{ id: string; text: string; overrunSeconds: number }> {
	const ordered = narratableComments(comments);
	const out: Array<{ id: string; text: string; overrunSeconds: number }> = [];
	for (let index = 0; index < ordered.length; index++) {
		const next = ordered[index + 1];
		if (!next) continue;
		const gap = (next.frame - ordered[index].frame) / fps;
		const needed =
			measured?.get(ordered[index].id) ?? estimateSeconds(ordered[index].text, speed);
		if (needed > gap) {
			out.push({
				id: ordered[index].id,
				text: ordered[index].text,
				overrunSeconds: Number((needed - gap).toFixed(2)),
			});
		}
	}
	return out;
}
